# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
#critical:
#    - '(critical|urgent)'

🪟 Windows:
    - '(🪟 Windows)'

🍎 Mac:
    - '(🍎 Mac)'

🐋 Docker:
    - '(🐋 Docker)'

📱 Termux:
    - '(📱 Termux)'

🐧 Linux:
    - '(🐧 Linux)'